[package]
name = "rust-calculate-sm3"
version = "0.1.0"
edition = "2024"

[dependencies]
sm3 = "0.4.2"
clap = { version = "4.0", features = ["derive"] }
[profile.release]
strip = true
debug = false
opt-level = 3